services:
  nvim:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        C_UID: 1002
        C_GID: 1002
    image: anes/elixirdev:latest
    volumes:
      - ./code:/workspace/code
      - ./local:/workspace/.local
    command:
      - bash
      - -c
      - while true; do sleep 2s; done
